data.raw["recipe"]["stone-furnace"].ingredients = {
    { type = "item", name = "stone", amount = 6 },
    { type = "item", name = "flint", amount = 3 }
}

data.raw["recipe"]["burner-mining-drill"].ingredients = {
    { type = "item", name = "wood-gear-wheel", amount = 1 },
    { type = "item", name = "brick", amount = 4 },
    { type = "item", name = "stone-furnace", amount = 1 }
}

--belts
data.raw["recipe"]["transport-belt"].ingredients = {
    { type = "item", name = "tin-plate", amount = 6 }
}

data.raw["recipe"]["underground-belt"].ingredients = {
    { type = "item", name = "tin-plate", amount = 10 },
    { type = "item", name = "transport-belt", amount = 2 }
}

data.raw["recipe"]["splitter"].ingredients = {
    { type = "item", name = "tin-plate", amount = 10 },
    { type = "item", name = "transport-belt", amount = 2 }
}

--disable vanilla ore processing
data.raw["recipe"]["iron-plate"].enabled = false
data.raw["recipe"]["copper-plate"].enabled = false

--disable vanilla technologies
local items = {
    "advanced-asteroid-processing",
    "advanced-circuit",
    "advanced-combinators",
    "advanced-material-processing",
    "advanced-material-processing-2",
    "advanced-oil-processing",
    "agricultural-science-pack",
    "agriculture",
    "artificial-soil",
    "artillery",
    "artillery-shell-damage-1",
    "artillery-shell-range-1",
    "artillery-shell-speed-1",
    "asteroid-productivity",
    "asteroid-reprocessing",
    "atomic-bomb",
    "automated-rail-transportation",
    "automation",
    "automation-2",
    "automation-3",
    "automation-science-pack",
    "automobilism",
    "bacteria-cultivation",
    "battery",
    "battery-equipment",
    "battery-mk2-equipment",
    "battery-mk3-equipment",
    "belt-immunity-equipment",
    "big-mining-drill",
    "biochamber",
    "bioflux",
    "bioflux-processing",
    "biolab",
    "biter-egg-handling",
    "braking-force-1",
    "braking-force-2",
    "braking-force-3",
    "braking-force-4",
    "braking-force-5",
    "braking-force-6",
    "braking-force-7",
    "bulk-inserter",
    "calcite-processing",
    "captive-biter-spawner",
    "captivity",
    "carbon-fiber",
    "chemical-science-pack",
    "circuit-network",
    "cliff-explosives",
    "coal-liquefaction",
    "concrete",
    "construction-robotics",
    "cryogenic-plant",
    "cryogenic-science-pack",
    "defender",
    "destroyer",
    "discharge-defense-equipment",
    "distractor",
    "effect-transmission",
    "efficiency-module",
    "efficiency-module-2",
    "efficiency-module-3",
    "electric-energy-accumulators",
    "electric-energy-distribution-1",
    "electric-energy-distribution-2",
    "electric-engine",
    "electric-mining-drill",
    "electric-weapons-damage-1",
    "electric-weapons-damage-2",
    "electric-weapons-damage-3",
    "electric-weapons-damage-4",
    "electromagnetic-plant",
    "electromagnetic-science-pack",
    "electronics",
    "elevated-rail",
    "energy-shield-equipment",
    "energy-shield-mk2-equipment",
    "engine",
    "epic-quality",
    "exoskeleton-equipment",
    "explosive-rocketry",
    "explosives",
    "fast-inserter",
    "fish-breeding",
    "fission-reactor-equipment",
    "flamethrower",
    "flammables",
    "fluid-handling",
    "fluid-wagon",
    "follower-robot-count-1",
    "follower-robot-count-2",
    "follower-robot-count-3",
    "follower-robot-count-4",
    "follower-robot-count-5",
    "foundation",
    "foundry",
    "fusion-reactor",
    "fusion-reactor-equipment",
    "gate",
    "gun-turret",
    "health",
    "heating-tower",
    "heavy-armor",
    "holmium-processing",
    "inserter-capacity-bonus-1",
    "inserter-capacity-bonus-2",
    "inserter-capacity-bonus-3",
    "inserter-capacity-bonus-4",
    "inserter-capacity-bonus-5",
    "inserter-capacity-bonus-6",
    "inserter-capacity-bonus-7",
    "jellynut",
    "kovarex-enrichment-process",
    "lamp",
    "land-mine",
    "landfill",
    "laser",
    "laser-shooting-speed-1",
    "laser-shooting-speed-2",
    "laser-shooting-speed-3",
    "laser-shooting-speed-4",
    "laser-shooting-speed-5",
    "laser-shooting-speed-6",
    "laser-shooting-speed-7",
    "laser-turret",
    "laser-weapons-damage-1",
    "laser-weapons-damage-2",
    "laser-weapons-damage-3",
    "laser-weapons-damage-4",
    "laser-weapons-damage-5",
    "laser-weapons-damage-6",
    "laser-weapons-damage-7",
    "legendary-quality",
    "lightning-collector",
    "lithium-processing",
    "logistic-robotics",
    "logistic-science-pack",
    "logistic-system",
    "logistics",
    "logistics-2",
    "logistics-3",
    "low-density-structure",
    "low-density-structure-productivity",
    "lubricant",
    "mech-armor",
    "metallurgic-science-pack",
    "military",
    "military-2",
    "military-3",
    "military-4",
    "military-science-pack",
    "mining-productivity-1",
    "mining-productivity-2",
    "mining-productivity-3",
    "modular-armor",
    "modules",
    "night-vision-equipment",
    "nuclear-fuel-reprocessing",
    "nuclear-power",
    "oil-gathering",
    "oil-processing",
    "overgrowth-soil",
    "personal-laser-defense-equipment",
    "personal-roboport-equipment",
    "personal-roboport-mk2-equipment",
    "physical-projectile-damage-1",
    "physical-projectile-damage-2",
    "physical-projectile-damage-3",
    "physical-projectile-damage-4",
    "physical-projectile-damage-5",
    "physical-projectile-damage-6",
    "physical-projectile-damage-7",
    "planet-discovery-aquilo",
    "planet-discovery-fulgora",
    "planet-discovery-gleba",
    "planet-discovery-vulcanus",
    "plastic-bar-productivity",
    "plastics",
    "power-armor",
    "power-armor-mk2",
    "processing-unit",
    "processing-unit-productivity",
    "production-science-pack",
    "productivity-module",
    "productivity-module-2",
    "productivity-module-3",
    "promethium-science-pack",
    "quality-module",
    "quality-module-2",
    "quality-module-3",
    "quantum-processor",
    "radar",
    "rail-support-foundations",
    "railgun",
    "railgun-damage-1",
    "railgun-shooting-speed-1",
    "railway",
    "recycling",
    "refined-flammables-1",
    "refined-flammables-2",
    "refined-flammables-3",
    "refined-flammables-4",
    "refined-flammables-5",
    "refined-flammables-6",
    "refined-flammables-7",
    "repair-pack",
    "research-productivity",
    "research-speed-1",
    "research-speed-2",
    "research-speed-3",
    "research-speed-4",
    "research-speed-5",
    "research-speed-6",
    "robotics",
    "rocket-fuel",
    "rocket-fuel-productivity",
    "rocket-part-productivity",
    "rocket-silo",
    "rocket-turret",
    "rocketry",
    "scrap-recycling-productivity",
    "solar-energy",
    "solar-panel-equipment",
    "space-platform",
    "space-platform-thruster",
    "space-science-pack",
    "speed-module",
    "speed-module-2",
    "speed-module-3",
    "spidertron",
    "stack-inserter",
    "steam-power",
    "steel-axe",
    "steel-plate-productivity",
    "steel-processing",
    "stone-wall",
    "stronger-explosives-1",
    "stronger-explosives-2",
    "stronger-explosives-3",
    "stronger-explosives-4",
    "stronger-explosives-5",
    "stronger-explosives-6",
    "stronger-explosives-7",
    "sulfur-processing",
    "tank",
    "tesla-weapons",
    "toolbelt",
    "toolbelt-equipment",
    "transport-belt-capacity-1",
    "transport-belt-capacity-2",
    "tree-seeding",
    "tungsten-carbide",
    "tungsten-steel",
    "turbo-transport-belt",
    "uranium-ammo",
    "uranium-mining",
    "uranium-processing",
    "utility-science-pack",
    "weapon-shooting-speed-1",
    "weapon-shooting-speed-2",
    "weapon-shooting-speed-3",
    "weapon-shooting-speed-4",
    "weapon-shooting-speed-5",
    "weapon-shooting-speed-6",
    "worker-robots-speed-1",
    "worker-robots-speed-2",
    "worker-robots-speed-3",
    "worker-robots-speed-4",
    "worker-robots-speed-5",
    "worker-robots-speed-6",
    "worker-robots-speed-7",
    "worker-robots-storage-1",
    "worker-robots-storage-2",
    "worker-robots-storage-3",
    "yumako"
}
for i=1, #items do
    if data.raw["technology"][items[i]] then
        data.raw["technology"][items[i]].enabled = false
    end
end

--add hand crafting
table.insert(data.raw["character"]["character"].crafting_categories, "hand")

--update some graphics
data.raw["item"]["iron-plate"].icon = "__gregtorio__/graphics/items/plates/iron-plate.png"
data.raw["item"]["copper-plate"].icon = "__gregtorio__/graphics/items/plates/copper-plate.png"